version: "0.1"

subdomains:
  dashboard-saleor-nullst-one-subdomain:
    dns_name: dashboard.saleor
    connections:
      domain: nullst-one-domain

apps:
  dashboard:
    module: nullstone/aws-fargate-service
    vars:
      cpu: 256
      memory: 512
      port: 80
    environment:
      BASE_DOMAIN: "saleor.{{ NULLSTONE_ENV }}.nullst.one"
      API_URI: "https://api.{{ BASE_DOMAIN }}/graphql/"
    capabilities:
      - module: nullstone/aws-load-balancer
        vars:
          health_check_path: "/"
        connections:
          subdomain: dashboard-saleor-nullst-one-subdomain
